### ISSUE TITLE
Migration "AddFieldsToProductXXXXXXXXX" has been failed, error: relation "file" does not exist

### ISSUE THREAD

**Issue by webface** [webface/medusa-custom#2]
```
Migration "AddFieldsToProduct1611063162650" has been failed, error: relation "file" does not exist
(node:33859) UnhandledPromiseRejectionWarning: QueryFailedError: relation "file" does not exist
    at QueryFailedError.TypeORMError [as constructor] (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:250:31)
    at step (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:124:57)
    at rejected (/Applications/MAMP/htdocs/ECOMMERCE/medusajs-ecommerce/medusa-js/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33859) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by webface** [comment]
@adrien2p thanks for looking into this
